version: '3.7'

services:
  slave:
    image: redis:6-alpine
    command: redis-server --slaveof ${REDIS_MASTER_IP} 6379
    ports:
      - "6379:6379"
    volumes:
      - "./.data-slave:/data"

  sentinel:
    build: 
      context: ./redis-sentinel
    environment:
      - REDIS_MASTER_IP=${REDIS_MASTER_IP}
      - SENTINEL_IP=${SENTINEL_IP}
      - SENTINEL_PORT=26379
    ports:
      - "26379:26379"