version: '3.7'

services:
  redis-slave:
    image: redis:7.0.5
    command: redis-server --slaveof ${REDIS_MASTER_IP} 6379
    ports:
      - "6379:6379"
    volumes:
      - "./.data-slave:/data"

  redis-sentinel:
    build: 
      context: ./redis-sentinel
    environment:
      - REDIS_MASTER_IP=${REDIS_MASTER_IP}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=1000
      - SENTINEL_FAILOVER=1000
      - SENTINEL_IP=${SENTINEL_IP}
      - SENTINEL_PORT=26379
    ports:
      - "26379:26379"