version: '3.7'

services:
  master:
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"

  sentinel:
    build: 
      context: ./redis-sentinel
    environment:
      - REDIS_MASTER_IP=${REDIS_MASTER_IP}
      - SENTINEL_IP=${REDIS_MASTER_IP}
      - SENTINEL_PORT=26379
    ports:
      - "26379:26379"
    links:
      - master
